
---

- import_tasks: apt.yml
  tags:
    - apt

- import_tasks: hostname.yml
  tags:
    - hostname

- import_tasks: locale.yml
  tags:
    - locale

- import_tasks: ssh.yml
  tags:
    - ssh

- import_tasks: timezone.yml
  tags:
    - timezone

- import_tasks: users.yml
  tags:
    - user