#cloud-config
groups:
  - ubuntu: [root,sys]

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: edwin
    gecos: Edwin Clement
    shell: /bin/bash
    primary_group: edwin
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    ssh_import_id:
      - gh:edwinclement08